### ISSUE TITLE
Black Member Insert NPE Issue 공유

### ISSUE THREAD

**Issue by JunyHarang** [woo00oo/goGetterProjectServer#55]
## Controller

```JAVA
package udodog.goGetterServer.controller.api.blackmember;

import io.swagger.annotations.*;
import lombok.RequiredArgsConstructor;
import org.springframework.data.domain.Pageable;
import org.springframework.data.domain.Sort;
import org.springframework.data.web.PageableDefault;
import org.springframework.hateoas.EntityModel;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;
import udodog.goGetterServer.model.converter.blackmember.BlackMemberEntityToModelConvertor;
import udodog.goGetterServer.model.dto.DefaultRes;
import udodog.goGetterServer.model.dto.request.BlackMemberManagementReqDto;
import udodog.goGetterServer.service.blackmember.BlackMemberManagementService;

import java.util.List;

@Api(tags = {"Black 회원 관리 API"})
@RestController
@RequiredArgsConstructor
public class BlackMemberManagementController {

    private final BlackMemberEntityToModelConvertor blackMemberEntityToModelConvertor;
    private final BlackMemberManagementService blackMemberManagementService;

    @ApiOperation(value = "블랙 회원 전체 조회 기능", notes = "Black Member 전체조회 기능 및 페이징 처리)")
    @ApiResponses(value = { @ApiResponse(code = 200, message = "1.조회 성공 \t\n 2.토큰 에러 \t\n 3.데이터 없음")})

    @GetMapping("/admapi/blackmembers")
    public ResponseEntity<EntityModel<DefaultRes<List<BlackMemberManagementReqDto>>>> searchBlackMember(
            @PageableDefault(sort = "blackMemberMgtId", direction = Sort.Direction.DESC, size = 15)Pageable pageable) { // Black 회원 조회 페이징 처리

        //        BlackMemberManagement bmm = new BlackMemberManagement();

        return new ResponseEntity<>(blackMemberEntityToModelConvertor
                                          .toModel(blackMemberManagementService.findAllBlackMember(pageable)), HttpStatus.OK);
    }  // searchBlackMember() 끝

    @ApiOperation(value = "블랙 회원 등록 API", notes = "블랙회원 등록 시 사용되는 API")
    @ApiResponses(value ={@ApiResponse(code = 200, message = "1. 등록성공 \t\n 2. 이미등록된회원")})

    @PostMapping("/admapi/blackmembers")    // Http Method 및 URI 설정
    public ResponseEntity<EntityModel<DefaultRes>> insertBlackMember(BlackMemberManagementReqDto bmmDto) { // Black 회원 등록

        return new ResponseEntity<>(blackMemberEntityToModelConvertor.toModel(blackMemberManagementService.insertBlackMember(bmmDto)), HttpStatus.OK);
    } // insertBlackMember() 끝


} // Class 끝
```

## Entity

```JAVA
package udodog.goGetterServer.model.entity;

import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import org.springframework.data.jpa.domain.support.AuditingEntityListener;
import org.springframework.data.util.Lazy;

import javax.persistence.*;

@Entity
@Getter
@NoArgsConstructor
public class BlackMemberManagement {

    @Id
    // 기본키 생성을 DB에 위임 시켜 준다. 즉, 자동 생성(시퀀스 넘버)
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long blackMemberMgtId;

    @OneToOne(targetEntity = User.class, fetch = FetchType.LAZY)
    // FK에 관련 설정
    @JoinColumn(name = "user_id")
    private User user;

    @Builder
    public BlackMemberManagement(User user) {
        this.user = user;
    } // 생성자 끝
} // Class End
```

## Repository

```JAVA
package udodog.goGetterServer.repository;

import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.data.jpa.repository.JpaRepository;
import udodog.goGetterServer.model.entity.BlackMemberManagement;

import java.util.Optional;

public interface BlackMemberManagementRepository extends JpaRepository<BlackMemberManagement, Long> {

    Page<BlackMemberManagement> findAllBy(Pageable pageable); // 모든 Black 회원 조회를 위한 추상 메서드

//    @Query("SELECT user FROM BlackMemberManagement WHERE user = :user")
    Optional<BlackMemberManagement> findByUser(Long id);
} // Class 끝
```

## Service

```JAVA
package udodog.goGetterServer.service.blackmember;

import lombok.RequiredArgsConstructor;
import org.modelmapper.ModelMapper;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.http.HttpStatus;
import org.springframework.stereotype.Service;
import udodog.goGetterServer.model.dto.DefaultRes;
import udodog.goGetterServer.model.dto.Pagination;
import udodog.goGetterServer.model.dto.request.BlackMemberManagementReqDto;
import udodog.goGetterServer.model.entity.BlackMemberManagement;
import udodog.goGetterServer.repository.BlackMemberManagementRepository;

import java.util.List;
import java.util.Optional;
import java.util.stream.Collectors;

@Service
@RequiredArgsConstructor
public class BlackMemberManagementService {

    private BlackMemberManagementRepository blackMemberManagementRepository;      // 블랙 회원 Repository 사용을 위한 인스턴스 변수 선언

    private ModelMapper modelMapper;
    public List<BlackMemberManagementReqDto> res(Page<BlackMemberManagement> page) {

        List<BlackMemberManagementReqDto> blackMemberList = page.stream().map(p -> modelMapper.map(p, BlackMemberManagementReqDto.class)).collect(Collectors.toList());

        return blackMemberList;
    } // res() 끝

    public DefaultRes<List<BlackMemberManagementReqDto>> findAllBlackMember(Pageable pageable) {

        Page<BlackMemberManagement> blackMemberPage = blackMemberManagementRepository.findAllBy(pageable);

        if(blackMemberPage.getTotalElements() == 0) {
            return DefaultRes.response(HttpStatus.OK.value(), "정보없음");

        } else {
            return DefaultRes.response(HttpStatus.OK.value(), "조회성공", res(blackMemberPage), new Pagination(blackMemberPage));
        }
    } // findAllBlackMember() 끝

    public DefaultRes insertBlackMember(BlackMemberManagementReqDto blackMemberManagementReqDto) {

        Long userId = blackMemberManagementReqDto.getId();
        Optional<BlackMemberManagement> bmm = blackMemberManagementRepository.findByUser(userId);

        if(bmm.equals(userId)) {
            return DefaultRes.response(HttpStatus.OK.value(), "기 등록된 회원");
        } else {
            return DefaultRes.response(HttpStatus.OK.value(), "등록가능");
        } // if - else 끝


        //        Long id = blackMemberManagement.getUser().getId();



//        Optional<BlackMemberManagement> optimalBlackMemberMgt = blackMemberManagementRepository.findByUser(id);
//
//            return optimalBlackMemberMgt.map(e -> DefaultRes.response(HttpStatus.OK.value(), "기 등록 회원")).orElseGet(() -> {
//               blackMemberManagementRepository.save(id);
//
//               return DefaultRes.response(HttpStatus.OK.value(), "등록 가능");
//            });

    } //insertBlackMember() 끝
} // Class 끝
```

## Convertor

```JAVA
package udodog.goGetterServer.controller.api.blackmember;

import io.swagger.annotations.*;
import lombok.RequiredArgsConstructor;
import org.springframework.data.domain.Pageable;
import org.springframework.data.domain.Sort;
import org.springframework.data.web.PageableDefault;
import org.springframework.hateoas.EntityModel;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;
import udodog.goGetterServer.model.converter.blackmember.BlackMemberEntityToModelConvertor;
import udodog.goGetterServer.model.dto.DefaultRes;
import udodog.goGetterServer.model.dto.request.BlackMemberManagementReqDto;
import udodog.goGetterServer.service.blackmember.BlackMemberManagementService;

import java.util.List;

@Api(tags = {"Black 회원 관리 API"})
@RestController
@RequiredArgsConstructor
public class BlackMemberManagementController {

    private final BlackMemberEntityToModelConvertor blackMemberEntityToModelConvertor;
    private final BlackMemberManagementService blackMemberManagementService;

    @ApiOperation(value = "블랙 회원 전체 조회 기능", notes = "Black Member 전체조회 기능 및 페이징 처리)")
    @ApiResponses(value = { @ApiResponse(code = 200, message = "1.조회 성공 \t\n 2.토큰 에러 \t\n 3.데이터 없음")})

    @GetMapping("/admapi/blackmembers")
    public ResponseEntity<EntityModel<DefaultRes<List<BlackMemberManagementReqDto>>>> searchBlackMember(
            @PageableDefault(sort = "blackMemberMgtId", direction = Sort.Direction.DESC, size = 15)Pageable pageable) { // Black 회원 조회 페이징 처리

        //        BlackMemberManagement bmm = new BlackMemberManagement();

        return new ResponseEntity<>(blackMemberEntityToModelConvertor
                                          .toModel(blackMemberManagementService.findAllBlackMember(pageable)), HttpStatus.OK);
    }  // searchBlackMember() 끝

    @ApiOperation(value = "블랙 회원 등록 API", notes = "블랙회원 등록 시 사용되는 API")
    @ApiResponses(value ={@ApiResponse(code = 200, message = "1. 등록성공 \t\n 2. 이미등록된회원")})

    @PostMapping("/admapi/blackmembers")    // Http Method 및 URI 설정
    public ResponseEntity<EntityModel<DefaultRes>> insertBlackMember(BlackMemberManagementReqDto bmmDto) { // Black 회원 등록

        return new ResponseEntity<>(blackMemberEntityToModelConvertor.toModel(blackMemberManagementService.insertBlackMember(bmmDto)), HttpStatus.OK);
    } // insertBlackMember() 끝


} // Class 끝

```

---

## Error Content

```TEXT
2021-06-25 11:53:43.650 ERROR 1222 --- [nio-8080-exec-4] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is java.lang.NullPointerException: Cannot invoke "udodog.goGetterServer.repository.BlackMemberManagementRepository.findByUser(java.lang.Long)" because "this.blackMemberManagementRepository" is null] with root cause

java.lang.NullPointerException: Cannot invoke "udodog.goGetterServer.repository.BlackMemberManagementRepository.findByUser(java.lang.Long)" because "this.blackMemberManagementRepository" is null
	at udodog.goGetterServer.service.blackmember.BlackMemberManagementService.insertBlackMember(BlackMemberManagementService.java:48) ~[main/:na]
	at udodog.goGetterServer.controller.api.blackmember.BlackMemberManagementController.insertBlackMember(BlackMemberManagementController.java:46) ~[main/:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:564) ~[na:na]
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:197) ~[spring-web-5.3.7.jar:5.3.7]
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:141) ~[spring-web-5.3.7.jar:5.3.7]
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:106) ~[spring-webmvc-5.3.7.jar:5.3.7]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:894) ~[spring-webmvc-5.3.7.jar:5.3.7]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:808) ~[spring-webmvc-5.3.7.jar:5.3.7]
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87) ~[spring-webmvc-5.3.7.jar:5.3.7]
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1063) ~[spring-webmvc-5.3.7.jar:5.3.7]
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:963) ~[spring-webmvc-5.3.7.jar:5.3.7]
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006) ~[spring-webmvc-5.3.7.jar:5.3.7]
	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:909) ~[spring-webmvc-5.3.7.jar:5.3.7]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:652) ~[tomcat-embed-core-9.0.46.jar:4.0.FR]
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883) ~[spring-webmvc-5.3.7.jar:5.3.7]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:733) ~[tomcat-embed-core-9.0.46.jar:4.0.FR]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:227) ~[tomcat-embed-core-9.0.46.jar:9.0.46]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) ~[tomcat-embed-core-9.0.46.jar:9.0.46]
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53) ~[tomcat-embed-websocket-9.0.46.jar:9.0.46]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) ~[tomcat-embed-core-9.0.46.jar:9.0.46]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) ~[tomcat-embed-core-9.0.46.jar:9.0.46]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:327) ~[spring-security-web-5.5.0.jar:5.5.0]
	at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:121) ~[spring-security-web-5.5.0.jar:5.5.0]
	at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:115) ~[spring-security-web-5.5.0.jar:5.5.0]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336) ~[spring-security-web-5.5.0.jar:5.5.0]
	at org.springframework.security.web.session.SessionManagementFilter.doFilter(SessionManagementFilter.java:126) ~[spring-security-web-5.5.0.jar:5.5.0]
	at org.springframework.security.web.session.SessionManagementFilter.doFilter(SessionManagementFilter.java:81) ~[spring-security-web-5.5.0.jar:5.5.0]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336) ~[spring-security-web-5.5.0.jar:5.5.0]
	at org.springframework.security.web.authentication.AnonymousAuthenticationFilter.doFilter(AnonymousAuthenticationFilter.java:105) ~[spring-security-web-5.5.0.jar:5.5.0]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336) ~[spring-security-web-5.5.0.jar:5.5.0]
	at org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter.doFilter(SecurityContextHolderAwareRequestFilter.java:149) ~[spring-security-web-5.5.0.jar:5.5.0]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336) ~[spring-security-web-5.5.0.jar:5.5.0]
	at org.springframework.security.web.savedrequest.RequestCacheAwareFilter.doFilter(RequestCacheAwareFilter.java:63) ~[spring-security-web-5.5.0.jar:5.5.0]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336) ~[spring-security-web-5.5.0.jar:5.5.0]
	at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:103) ~[spring-security-web-5.5.0.jar:5.5.0]
	at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:89) ~[spring-security-web-5.5.0.jar:5.5.0]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336) ~[spring-security-web-5.5.0.jar:5.5.0]
	at org.springframework.web.filter.CorsFilter.doFilterInternal(CorsFilter.java:91) ~[spring-web-5.3.7.jar:5.3.7]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) ~[spring-web-5.3.7.jar:5.3.7]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336) ~[spring-security-web-5.5.0.jar:5.5.0]
	at org.springframework.security.web.header.HeaderWriterFilter.doHeadersAfter(HeaderWriterFilter.java:90) ~[spring-security-web-5.5.0.jar:5.5.0]
	at org.springframework.security.web.header.HeaderWriterFilter.doFilterInternal(HeaderWriterFilter.java:75) ~[spring-security-web-5.5.0.jar:5.5.0]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) ~[spring-web-5.3.7.jar:5.3.7]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336) ~[spring-security-web-5.5.0.jar:5.5.0]
	at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:110) ~[spring-security-web-5.5.0.jar:5.5.0]
	at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:80) ~[spring-security-web-5.5.0.jar:5.5.0]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336) ~[spring-security-web-5.5.0.jar:5.5.0]
	at org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter.doFilterInternal(WebAsyncManagerIntegrationFilter.java:55) ~[spring-security-web-5.5.0.jar:5.5.0]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) ~[spring-web-5.3.7.jar:5.3.7]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336) ~[spring-security-web-5.5.0.jar:5.5.0]
	at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:211) ~[spring-security-web-5.5.0.jar:5.5.0]
	at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:183) ~[spring-security-web-5.5.0.jar:5.5.0]
	at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:358) ~[spring-web-5.3.7.jar:5.3.7]
	at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:271) ~[spring-web-5.3.7.jar:5.3.7]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) ~[tomcat-embed-core-9.0.46.jar:9.0.46]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) ~[tomcat-embed-core-9.0.46.jar:9.0.46]
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100) ~[spring-web-5.3.7.jar:5.3.7]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) ~[spring-web-5.3.7.jar:5.3.7]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) ~[tomcat-embed-core-9.0.46.jar:9.0.46]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) ~[tomcat-embed-core-9.0.46.jar:9.0.46]
	at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93) ~[spring-web-5.3.7.jar:5.3.7]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) ~[spring-web-5.3.7.jar:5.3.7]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) ~[tomcat-embed-core-9.0.46.jar:9.0.46]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) ~[tomcat-embed-core-9.0.46.jar:9.0.46]
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201) ~[spring-web-5.3.7.jar:5.3.7]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) ~[spring-web-5.3.7.jar:5.3.7]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) ~[tomcat-embed-core-9.0.46.jar:9.0.46]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) ~[tomcat-embed-core-9.0.46.jar:9.0.46]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202) ~[tomcat-embed-core-9.0.46.jar:9.0.46]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97) ~[tomcat-embed-core-9.0.46.jar:9.0.46]
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:542) ~[tomcat-embed-core-9.0.46.jar:9.0.46]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:143) ~[tomcat-embed-core-9.0.46.jar:9.0.46]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92) ~[tomcat-embed-core-9.0.46.jar:9.0.46]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78) ~[tomcat-embed-core-9.0.46.jar:9.0.46]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:357) ~[tomcat-embed-core-9.0.46.jar:9.0.46]
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:374) ~[tomcat-embed-core-9.0.46.jar:9.0.46]
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65) ~[tomcat-embed-core-9.0.46.jar:9.0.46]
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:893) ~[tomcat-embed-core-9.0.46.jar:9.0.46]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1707) ~[tomcat-embed-core-9.0.46.jar:9.0.46]
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) ~[tomcat-embed-core-9.0.46.jar:9.0.46]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) ~[na:na]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) ~[tomcat-embed-core-9.0.46.jar:9.0.46]
	at java.base/java.lang.Thread.run(Thread.java:832) ~[na:na]


```

---

## 요청사항

**블랙 회원 등록**이라면 회원 목록 중 등록 버튼을 눌러 블랙 회원을 등록시켜주어야 하니 RequestDTO가 필요하다고 판단이 되는데, 현재 **RequestDTO가 NULL**인데, 이걸 어떻게 해결할 수 있을지 잘 모르겠습니다.

**Comment by woo00oo** [comment]
서비스에서 레파지토리 의존성 주입이 제대로 안됐네요!
의존성 주입에 대해 알아보시면 될 거 같습니다

**Comment by JunyHarang** [comment]
답변 감사합니다!

**Comment by JunyHarang** [comment]
Issues Number #60에 의거 본 Issue Close 처리 하겠습니다.
